# Generated by Django 4.0.5 on 2022-06-26 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_catagory_product_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='subcetagory',
            new_name='subcategory',
        ),
    ]
